/* Principal.java 28/02/2018
 * copyrigth (c) 2018 Jesus Roso, David Manosalba, Francisco Barrero
 */
package GUI.interfaz;

/**
 * la clase Bebidas contiene los botones paara elegir un tipo de bebida
 * y despues manda los datos a la clase interfaz que los muetra seleccionando
 * el boton imprimir
 * @author Jesus Roso
 * @author David Manosalba
 * @author Francisco Barrero
 * @version 1.4
 */
public class Bebidas extends javax.swing.JFrame {

    /**
     * Creates new form Bebidas
     */
    public Bebidas() {
        initComponents();
    }
    //variable estatica que almacena lo seleccionado en bebidas
    public static String gb = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbjugos = new javax.swing.JComboBox<>();
        cbgaseosa = new javax.swing.JComboBox<>();
        cblicores = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jBguardarjugo = new javax.swing.JButton();
        jBguardargaseosa = new javax.swing.JButton();
        jBguardarlicor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbjugos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR JUGO", "Jugo de mora", "Jugo de mango", "Jugo de guayaba", "Jugo de lulo", " " }));

        cbgaseosa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR GASEOSA", "Cocacola", "Quatro", "7-up", "Postobon", " ", " " }));
        cbgaseosa.setToolTipText("");

        cblicores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE LICOR", "Cerveza", "Vino", "Coctel", "Aguardiente", " " }));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 12)); // NOI18N
        jLabel1.setText("SELECCIONE BEBIDA QUE DESEA PARA EL MENU");

        jBguardarjugo.setText("Guardar jugo");
        jBguardarjugo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarjugoActionPerformed(evt);
            }
        });

        jBguardargaseosa.setText("Guardar Gaseosa");
        jBguardargaseosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardargaseosaActionPerformed(evt);
            }
        });

        jBguardarlicor.setText("Guardar Licor");
        jBguardarlicor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarlicorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jBguardarjugo)
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jBguardargaseosa))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbgaseosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbjugos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cblicores, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(136, 136, 136))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBguardarlicor)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(cbjugos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBguardarjugo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbgaseosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBguardargaseosa)
                .addGap(24, 24, 24)
                .addComponent(cblicores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBguardarlicor)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBguardarjugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarjugoActionPerformed
        // seleccione lo seleccionado en el box lo asigna a la variable y cierra la ventana
             gb=cbjugos.getSelectedItem().toString();
             this.setVisible(false);
    }//GEN-LAST:event_jBguardarjugoActionPerformed

    private void jBguardargaseosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardargaseosaActionPerformed
        // seleccione lo seleccionado en el box lo asigna a la variable y cierra la ventana
        gb=cbgaseosa.getSelectedItem().toString();
        this.setVisible(false);
    }//GEN-LAST:event_jBguardargaseosaActionPerformed

    private void jBguardarlicorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarlicorActionPerformed
        // seleccione lo seleccionado en el box lo asigna a la variable y cierra la ventana
        gb=cblicores.getSelectedItem().toString();
        this.setVisible(false);
    }//GEN-LAST:event_jBguardarlicorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbgaseosa;
    private javax.swing.JComboBox<String> cbjugos;
    private javax.swing.JComboBox<String> cblicores;
    private javax.swing.JButton jBguardargaseosa;
    private javax.swing.JButton jBguardarjugo;
    private javax.swing.JButton jBguardarlicor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
