/* Principal.java 28/02/2018
 * copyrigth (c) 2018 Jesus Roso, David Manosalba, Francisco Barrero
 */
package GUI.interfaz;
/**
 * la clase Entrada tiene unos botones para escoger entre sopa y fruta
 * y esos datos los envia a la interfaz que despues los muestra 
 * a traves del boton imprimir
 * @author Jesus Roso
 * @author David Manosalba
 * @author Francisco Barrero
 * @version 1.4
 */
public class Entrada extends javax.swing.JFrame {

    /**
     * Creates new form Entrada
     */
    public Entrada() {
        initComponents();
    }
    // variable statica que almacene la entrada seleccionada
        public static String gs = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbsopa = new javax.swing.JComboBox<>();
        cbfruta = new javax.swing.JComboBox<>();
        jBguardarsopa = new javax.swing.JButton();
        jBguardarfruta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbsopa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE LA SOPA", "Sopa de arroz", "Ajiaco", "Sopa de pasta", "Caldo de costilla" }));
        cbsopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsopaActionPerformed(evt);
            }
        });

        cbfruta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR FRUTA", "Papaya", "Manzana", "Pera", "Melon" }));

        jBguardarsopa.setText("Guarda sopa ");
        jBguardarsopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarsopaActionPerformed(evt);
            }
        });

        jBguardarfruta.setText("Guardar Fruta");
        jBguardarfruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarfrutaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 12)); // NOI18N
        jLabel1.setText("SELECCIONE ENTRADA QUE DESEA PARA EL MENU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbfruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbsopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBguardarsopa)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBguardarfruta)
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(cbsopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBguardarsopa)
                .addGap(18, 18, 18)
                .addComponent(cbfruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBguardarfruta)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //box con diferentes opciones de entrada
    private void cbsopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsopaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsopaActionPerformed

    private void jBguardarsopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarsopaActionPerformed
        // guarda los seleccionado en el voz en la variable gs y cierra la ventana
        gs=cbsopa.getSelectedItem().toString();
        this.setVisible(false);
    }//GEN-LAST:event_jBguardarsopaActionPerformed

    private void jBguardarfrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarfrutaActionPerformed
        // guarda los seleccionado en el voz en la variable gs y cierra la ventana
        gs=cbfruta.getSelectedItem().toString();
        this.setVisible(false);
    }//GEN-LAST:event_jBguardarfrutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbfruta;
    private javax.swing.JComboBox<String> cbsopa;
    private javax.swing.JButton jBguardarfruta;
    private javax.swing.JButton jBguardarsopa;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
