/* Principal.java 28/02/2018
 * copyrigth (c) 2018 Jesus Roso, David Manosalba, Francisco Barrero
 */
package GUI.interfaz;

import javax.swing.JOptionPane;

/**
 * la class interface contiene todo los botones para ingresar a las otraz interfaces 
 * e imprime el menu una vez seleccionado los items
 * @author Jesus Roso
 * @author David Manosalba
 * @author Francisco Barrero
 * @version 1.4
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox1 = new java.awt.Checkbox();
        jPanel1 = new javax.swing.JPanel();
        jBentrada = new javax.swing.JButton();
        jBprincipal = new javax.swing.JButton();
        jBbebidas = new javax.swing.JButton();
        jBpostre = new javax.swing.JButton();
        jBimprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLentradati = new javax.swing.JLabel();
        jLentrada = new javax.swing.JLabel();
        jLPrincipalti = new javax.swing.JLabel();
        jLbebidati = new javax.swing.JLabel();
        jLbebida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLpostre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextprincipal = new javax.swing.JTextArea();

        checkbox1.setLabel("checkbox1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBentrada.setText("ENTRADA");
        jBentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBentradaActionPerformed(evt);
            }
        });

        jBprincipal.setText("PRINCIPAL");
        jBprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprincipalActionPerformed(evt);
            }
        });

        jBbebidas.setText("BEBIDAS");
        jBbebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbebidasActionPerformed(evt);
            }
        });

        jBpostre.setText("POSTRE");
        jBpostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpostreActionPerformed(evt);
            }
        });

        jBimprimir.setText("IMPRIMIR");
        jBimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBimprimirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 18)); // NOI18N
        jLabel1.setText("MENU");

        jLentradati.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 12)); // NOI18N
        jLentradati.setText("Entrada");

        jLentrada.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 11)); // NOI18N

        jLPrincipalti.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 12)); // NOI18N
        jLPrincipalti.setText("Principal");

        jLbebidati.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 12)); // NOI18N
        jLbebidati.setText("Bebida");

        jLbebida.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 12)); // NOI18N
        jLabel2.setText("Postre");

        jLpostre.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 11)); // NOI18N

        jTextprincipal.setColumns(20);
        jTextprincipal.setRows(5);
        jScrollPane1.setViewportView(jTextprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLbebidati)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLpostre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBimprimir)
                                .addGap(24, 24, 24))
                            .addComponent(jLbebida, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLentradati))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLPrincipalti, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBentrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBprincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBbebidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBpostre)))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLentradati)
                .addGap(18, 18, 18)
                .addComponent(jLentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLPrincipalti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbebidati)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbebida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLpostre, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBprincipal)
                    .addComponent(jBbebidas)
                    .addComponent(jBpostre)
                    .addComponent(jBentrada))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBentradaActionPerformed
        // objeto que llama a la interfaz entrada y la hace visible
        Entrada abrir = new Entrada();
        abrir.setVisible(true);
        
    }//GEN-LAST:event_jBentradaActionPerformed

    private void jBprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprincipalActionPerformed
        // objeto que llama a la interfaz principal y la hace visible
        Principal abrir = new Principal();
        abrir.setVisible(true);
    }//GEN-LAST:event_jBprincipalActionPerformed

    private void jBbebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbebidasActionPerformed
        // objeto que llama a la interfaz bebidas y la hace visible
        Bebidas abrir = new Bebidas();
        abrir.setVisible(true);
    }//GEN-LAST:event_jBbebidasActionPerformed

    private void jBpostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpostreActionPerformed
       // objeto que llama a la interfaz postres y la hace visible
        Postre abrir = new Postre ();
        abrir.setVisible(true);
    }//GEN-LAST:event_jBpostreActionPerformed

    @SuppressWarnings("static-access")
    private void jBimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBimprimirActionPerformed
        // llama las variables de las otras interfaces y las imprime en los jLabel y jtext de interfaces
        Principal verp = new Principal();
        Entrada vere = new Entrada();
        Bebidas verb = new Bebidas ();
        Postre  verd = new Postre ();
        jLentrada.setText(vere.gs);
        jTextprincipal.setText(verp.h+"\n"+verp.g+"\n"+verp.p+"\n"+verp.v);
        jLbebida.setText(verb.gb);
        jLpostre.setText(verd.gp);
       
        
    }//GEN-LAST:event_jBimprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton jBbebidas;
    private javax.swing.JButton jBentrada;
    private javax.swing.JButton jBimprimir;
    private javax.swing.JButton jBpostre;
    private javax.swing.JButton jBprincipal;
    private javax.swing.JLabel jLPrincipalti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbebida;
    private javax.swing.JLabel jLbebidati;
    private javax.swing.JLabel jLentrada;
    private javax.swing.JLabel jLentradati;
    private javax.swing.JLabel jLpostre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextprincipal;
    // End of variables declaration//GEN-END:variables
}
